apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-lxcfs-admission-webhook-cfg
  namespace: kube-system
  labels:
    app: lxcfs-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: kube-system/lxcfs-webhook-server-cert
webhooks:
  - name: validation-lxcfs-admission-webhook-svc.kube-system.svc
    clientConfig:
      service:
        name: lxcfs-admission-webhook-svc
        namespace: kube-system
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    timeoutSeconds: 15
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        lxcfs-admission-webhook: enabled